#include "signal-handler.h"

#include <signal.h>
#include <stdio.h>
#include <sys/signalfd.h>
#include <sys/types.h>
#include <unistd.h>

#include "block.h"
#include "timer.h"

typedef struct signalfd_siginfo signal_info;

signal_handler signal_handler_new(block_arr blocks) {
    signal_handler handler = {
        .blocks = blocks,
    };
    return handler;
}

int signal_handler_init(signal_handler *const handler) {
    signal_set set;
    (void)sigemptyset(&set);

    // Handle SIGALRM generated by the timer.
    (void)sigaddset(&set, TIMER_SIGNAL);

    // Handle termination signals.
    (void)sigaddset(&set, SIGINT);
    (void)sigaddset(&set, SIGTERM);

    for (unsigned short i = 0; i < handler->blocks.length; ++i) {
        const block *const block = &handler->blocks.values[i];
        if (block->event_id > 0) {
            if (sigaddset(&set, SIGRTMIN + block->event_id) != 0) {
                (void)fprintf(
                    stderr,
                    "error: invalid or unsupported signal specified for "
                    "\"%s\" block\n",
                    block->command);
                return 1;
            }
        }
    }

    // Create a signal file descriptor for epoll to watch.
    handler->fd = signalfd(-1, &set, 0);
    if (handler->fd == -1) {
        (void)fprintf(stderr,
                      "error: could not create file descriptor for signals\n");
        return 1;
    }

    // Block all realtime and handled signals.
    for (int i = SIGRTMIN; i <= SIGRTMAX; ++i) {
        (void)sigaddset(&set, i);
    }
    (void)sigprocmask(SIG_BLOCK, &set, NULL);

    return 0;
}

int signal_handler_deinit(signal_handler *const handler) {
    if (close(handler->fd) != 0) {
        (void)fprintf(stderr,
                      "error: could not close signal file descriptor\n");
        return 1;
    }

    return 0;
}

int signal_handler_read(signal_handler *const handler) {
    signal_info info;
    const ssize_t bytes_read = read(handler->fd, &info, sizeof(info));
    if (bytes_read == -1) {
        (void)fprintf(stderr, "error: could not read info of incoming signal");
        return 1;
    }
    return (int)info.ssi_signo;
}
